services:
  client:
    container_name: spius_client
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /client/node_modules
    ports:
      - 3000:${PORT}
    networks:
      - student-information-update-system_spius
networks:
  student-information-update-system_spius:
    external: true
