/academic-profiles:
  get:
    summary: Get academic profiles
    tags: [Academic Profiles]
    security:
      - bearerAuth: []
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/responseSuccess"
                - type: object
                  properties:
                    data:
                      type: array
                      items:
                        allOf:
                          - $ref: "#/components/schemas/_id"
                          - $ref: "#/components/schemas/userId"
                          - $ref: "#/components/schemas/acadProfile"
                          - $ref: "#/components/schemas/date"
      400:
        $ref: "#/components/responses/badRequest"
      401:
        $ref: "#/components/responses/unauthorized"
      404:
        $ref: "#/components/responses/notFound"
      500:
        $ref: "#/components/responses/internalServerError"
  post:
    summary: Create academic profile
    tags: [Academic Profiles]
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/acadProfile"
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/_id"
                - $ref: "#/components/schemas/userId"
                - $ref: "#/components/schemas/acadProfile"
                - $ref: "#/components/schemas/date"
      400:
        $ref: "#/components/responses/badRequest"
      401:
        $ref: "#/components/responses/unauthorized"
      404:
        $ref: "#/components/responses/notFound"
      500:
        $ref: "#/components/responses/internalServerError"
