/roles:
  get:
    summary: Get roles
    tags: [Roles]
    security:
      - bearerAuth: []
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/_id"
                - $ref: "#/components/schemas/role"
                - $ref: "#/components/schemas/date"
      400:
        $ref: "#/components/responses/badRequest"
      404:
        $ref: "#/components/responses/unauthorized"
      500:
        $ref: "#/components/responses/internalServerError"
